### ISSUE TITLE
problem after installation

### ISSUE THREAD

**Issue by arthur33974** [dbarzin/pandora-box#10]
Hello, I followed the documentation to install this white station solution, however after restarting the machine, the image "please insert your USB keys" is only displayed if I am connected by ssh to the machine. Furthermore, after inserting my USB key, I see "your USB key is being scanned" then it goes back to the home page without displaying anything more. I can't change anything because I don't have access to anything in ssh it just connects me then black terminal. Could you please help me.

**Comment by arthur33974** [comment]
I can access the machine via ssh by opening a second ssh session

**Comment by dbarzin** [comment]
The keys ALT-F1, ALT-F2, ALT-F3... allows you to switch to another terminal.

Have you installed Ubuntu 22.04 ?
Could you try to run the tests programs in this folder https://github.com/dbarzin/pandora-box/tree/main/tests ?

**Comment by arthur33974** [comment]
Bonjour, désolé de répondre si tardivement, c'est bon j'ai réussi effectivement le premier terminal est une page noir il fallait changé de terminal. Merci
