### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by schoolliu** [dbarzin/pandora-box#13]
'sudo apt install -y git' after the command is executed;

The following commands cannot be directly executed

`git clone https://github.com/dbarzin/pandora-box`
You need to switch to the root user

**Comment by dbarzin** [comment]
Normally, you do not need to be root to clone a folder with git.
Are you able to write on the folder you are in ?
To help you, could you send me the result of these commands :

```
whoami
pwd
```

**Comment by schoolliu** [comment]
pandora@pandora:~$ 
pandora@pandora:~$ whoami
pandora
pandora@pandora:~$ 
pandora@pandora:~$ pwd
/home/pandora
pandora@pandora:~$

**Comment by dbarzin** [comment]
OK, this is excellent and what happen when you type : 

    git clone https://github.com/dbarzin/pandora-box

**Comment by schoolliu** [comment]
pandora@pandora:~$ 
pandora@pandora:~$ git clone https://github.com/dbarzin/pandora-box
Cloning into 'pandora-box'...
fatal: unable to access 'https://github.com/dbarzin/pandora-box/': Failed to connect to github.com port 443 after 133988 ms: Couldn't connect to server

------------------------------------

Thank you for your answer.
Maybe it's my network,
But when I use root there is no problem.
