### ISSUE TITLE
Can't scan 2 USBs devices in a single boot

### ISSUE THREAD

**Issue by Matchag** [dbarzin/pandora-box#14]
Hi, fresh install here

I've followed the instructions to install, just modified the CURSES to False in the pandora-box.ini file

When I'm scanning a USB device with eicar.txt to test it, it triggers it and ask to delete it. But, in the log, it displays that databases are shutdown :

2024-06-20 16:38:33,398 WorkersManager INFO:Not implemented, nothing to wait for.
2024-06-20 16:38:33,403 WorkersManager INFO:Shutting down WorkersManager
2024-06-20 16:38:33,864 Website INFO:Sending 2 to 1076.
2024-06-20 16:38:34,864 Website INFO:Sending 9 to 1076.
2024-06-20 16:38:35,866 Website WARNING:Unable to kill 1076, keep sending SIGKILL
2024-06-20 16:38:35,896 Website INFO:Shutting down Website
Got a dead script: background_processing - 1079
Got a dead script: website - 1080
[('background_processing', 1.0), ('website', 1.0)]
[('background_processing', 1.0)]
[('background_processing', 1.0)]
Redis cache database shutdown.
Kvrocks storage database shutdown.
Shutting down databases...
done.

When I'm trying to restart them, it don't work. Am I doing something wrong ?

I have to reboot to restart everything, and then I can scan an other USB device

Thank you in advance

**Comment by dbarzin** [comment]
I have to install two stations next week. I will check that.

**Comment by Matchag** [comment]
Thank you, I'm adding that it's completely working on the first scan, just the others without rebooting are not working and the GUI Interface saying everything is okay

**Comment by dbarzin** [comment]
I have reinstalled a workstation this weekend, but I have not been able to reproduce this issue.
After several scans, the workstation is still working.
Could you check these :
- Have you followed the installation procedure ?
- Did you get any issue during the installation ?
- What is the configuration of the computer running pandora-box (CPU, RAM, Disk) ?
- Is there an error in the logs (/var/log/pandora-box.log) ?

**Comment by dbarzin** [comment]
No answer, could not reproduce issue.
