### ISSUE TITLE
Pas de curseur

### ISSUE THREAD

**Issue by masterbalby2** [dbarzin/pandora-box#15]
Bonjour,

j'ai installé sur un tiny M715q pandora-box.
Par défaut l'interface qui se lance est le mode graphique.

Lorsque je connecte une clef avec 1 virus le bouton rouge "Cliquer ici pour désinfecter" apparaît.
Mais je n'ai aucun curseur qui me permette de cliquer. Existe-t-il un raccourci pour lancer le nettoyage ?

Autre question.
Comment changer de mode et passer en mode texte.

Merci par avance.

PS : Pandora-box est exactement le système que je recherchai pour mon entreprise.

**Comment by dbarzin** [comment]
Pour passer en mode texte par défaut, il faut modifier le fichier pandora-box.ini et mettre :

    CURSES = True

Il n'est pas possible de passer d'un mode à l'autre sans relancer l'application.

Pour lancer le nettoyage, il faut pousser `Enter` ou cliquer sur l'écran (si vous avez un écran sensible).

**Comment by masterbalby2** [comment]
Ok merci pour cette réponse rapide.
Parfois lorsque j'appuie sur Entrée avec certaine clés vérolées le système freeze.
Des idées de pourquoi ?

**Comment by dbarzin** [comment]
Il y a une erreur dans les logs (/var/logs/pandora-box.log) ?

**Comment by masterbalby2** [comment]
j'ai des erreurs de permissions 
```
08/04/24 00:05 - boxname="pandora", device-inserted
08/04/24 00:05 - boxname="pandora", device_name="/dev/sda1, path_id="pci-0000:00:14.0-usb-0:3:1.0-scsi-0:0:0:0", bus system="usb", USB_driver="usb-storage", device_type="partition", device_usage="filesystem", partition type="dos", fs_type="hfsplus", partition_label="Sans_titre", device_model="USB_Flash_Drive", model_id="4300", serial_short="dev.get("ID_SERIAL_SHORT")", serial="dev.get("ID_SERIAL")"
08/04/24 00:05 - boxname="pandora", error="[Errno 13] Permission denied: '/media/box/.journal'"
Traceback (most recent call last):
  File "/home/pandora/pandora-box/pandora-box.py", line 118, in scan
    res = self.pandora.submit_from_disk(file)
  File "/home/pandora/.local/lib/python3.10/site-packages/pypandora/api.py", line 74, in submit_from_disk
    with file_on_disk.open('rb') as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
PermissionError: [Errno 13] Permission denied: '/media/box/.journal'
08/04/24 00:05 - boxname="pandora", error="[Errno 13] Permission denied: '/media/box/.journal_info_block'"
Traceback (most recent call last):
  File "/home/pandora/pandora-box/pandora-box.py", line 118, in scan
    res = self.pandora.submit_from_disk(file)
  File "/home/pandora/.local/lib/python3.10/site-packages/pypandora/api.py", line 74, in submit_from_disk
    with file_on_disk.open('rb') as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
PermissionError: [Errno 13] Permission denied: '/media/box/.journal_info_block'
```

**Comment by dbarzin** [comment]
As-tu fait l'installation avec Ubuntu ? 
As-tu eu des erreurs lors de l'installation ?
Il faut vérifier pourquoi l'utilisateur Pandora ne peut pas écrire sur la clé USB ?
La clé est-elle en mode read-only ?

**Comment by masterbalby2** [comment]
Ok
Je viens de tester plusieurs clé et il y en a qu'une seule qui me fait ça.
je ferais plus de tests lundi au boulot.
Merci pour cet outil qui va me simplifier la vie
