### ISSUE TITLE
WARNING: Package(s) not found: yara-python

### ISSUE THREAD

**Issue by Foxi352** [dbarzin/pandora-box#2]
```
swagener@pandora-box-1:~/pandora-box$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy
```
Install.sh yells:
`WARNING: Package(s) not found: yara-python`

Source probably: 
`su - $SUDO_USER -c "python3 -m pip show yara-python"`

^^ This should be `pip install` and not `pip show` ?

Maybe this is not needed at all: https://github.com/pandora-analysis/pandora/issues/77#issuecomment-1175884288

**Comment by dbarzin** [comment]
Yes, it is a work in progress. I have to retest the whole process.
Come back in a few days.
