### ISSUE TITLE
cp: missing file operand

### ISSUE THREAD

**Issue by Foxi352** [dbarzin/pandora-box#3]
./install.sh yells multiple lines with:
```
cp: missing file operand
Try 'cp --help' for more information.
```
To fix change:
`su - $SUDO_USER -c "cd pandora; for file in pandora/workers/*.sample; do cp -i ${file} ${file%%.sample}; done"`
to:
`su - $SUDO_USER -c "cd ~/pandora; for file in pandora/workers/*.sample; do cp -i ${file} ${file%%.sample}; done"`

**Comment by dbarzin** [comment]
Fixed !
