### ISSUE TITLE
Problème d'installation avec la commande ./install.sh

### ISSUE THREAD

**Issue by Bastien-2023** [dbarzin/pandora-box#8]
Bonjour,

Je me permets de vous écrire ce message pour vous demander si c'était normal lors de la commande ./install.sh le script s'arrêtait avec comme erreur "install.sh: line 110: cd: /home/root/pandora: No such file or directory".

Suite à cette erreur, j'ai installé manuellement pandora à la racine de ma machine. Puis j'ai relancé le script qui est passé outre l'erreur d'au-dessus. Mais un nouveau problème  est survenue.

 Ce message est le suivant "./run_kvrocks.sh: line6: ../../kvorcks/build/kvrocks: No such file or directory

Wainting on storage to start .....
Wainting on storage to start .....
Wainting on storage to start .....
Wainting on storage to start .....
Wainting on storage to start .....
Ce message a l'infini.

Avez-vous une solution à ce problème ?

Cordialement

**Comment by dbarzin** [comment]
Cela fait un moment que je n'ai pas installé de pandora-box.  Je vais vérifier.

**Comment by dbarzin** [comment]
Le problème avec l'erreur dans le script d'installation est corrigé.
Pour kvrocks, je suis encore occupé.

**Comment by dbarzin** [comment]
L'installation est fixée mais je n'ai pas encore essayé cette nouvelle version en production.

**Comment by Bastien-2023** [comment]
> L'installation est établi mais je n'ai pas encore plus essayé cette nouvelle version en production.

Bonjour, merci pour vos corrections, je vais tester de mon côté.
Je reviendrai vers vous pour vous dire si cela à fonctionner.

**Comment by Bastien-2023** [comment]
> L'installation est établi mais je n'ai pas encore plus essayé cette nouvelle version en production.

Bonjour, je reviens vers vous, car l'installation, c'est termine sans erreurs, mis à part une erreur dans le script à la ligne 124.

Ou vous avez écrit :      apt-get install -y dhparm clamav-daemon
Au lieu de :                   apt-get install -y hdparm clamav-daemon

Suite à cette modification, l'installation se termine sans erreurs.

Seulement quand on finit cette installation, il nous est dit de redémarrer le serveur, ce que je fais et au démarrage de ce dernier rien ne se passe mis à part un enchainement de cinq images au format PNG qui défilent quand j'ouvre le terminal du serveur.

C'est cinq images me disent d'insérer une clé USB, mais dès que cette dernière est insérée, rien ne se passe.

Je suis sur un Ubuntu 22.04 en version graphique.

Vous retrouverez en pièce jointe une capture d'écran de l'erreur.
![Pièce jointe](https://github.com/dbarzin/pandora-box/assets/149511448/6cfe9204-7b45-4cb6-a5b0-de0fa7ba84c0)

**Comment by dbarzin** [comment]
Vous devez utiliser la version d'Ubuntu 22.04 server LTS et choisir lors de l'installation (x) Ubuntu Server (minimized).
Cela permet de lancer la borne sans XWindows.

Pour la clé USB, vous pouvez activer la configuration pour Ubuntu :

    cp pandora-box.ini.ubuntu pandora-box.ini

Cela devrait fonctionner.

**Comment by dbarzin** [comment]
Je viens de réinstaller une borne avec la nouvelle version. Cela fonctionne !

**Comment by Bastien-2023** [comment]
> Je viens de réinstaller une borne avec la nouvelle version. Cela fonctionne

D'accord merci de votre réponse.

**Comment by Bastien-2023** [comment]
> Je viens de réinstaller une borne avec la nouvelle version. Cela fonctionne

Bonjour, je me permets de revenir vers vous non pas pour un problème d'installation, mais un problème de redémarrage. Le problème est le suivant, une fois l'installation terminée, un message s'affiche  "You may reboot the server.".

 Ce que je fais, mais une fois redémarrait, j'ai tous les messages avec écrit "OK" en vert et part la suite plus rien, juste une barre d'insertion qui clignote en haut à gauche de l'écran.

Savez-vous peut-être de quoi il s'agit ?

Cordialement

**Comment by dbarzin** [comment]
Si vous avez installé Pandora-box dans une VM, la borne ne s'affiche pas dans la console (pas trouvé de correction).
Vous devez vous connecter SSH, vous aurez la console de Pandora-box qui démarre dans le terminal.
Pour cela, il faut installer open-ssh et rediriger le port 22 de la VM sur un port de votre poste de travail.
