### ISSUE TITLE
Error in install script

### ISSUE THREAD

**Issue by Foxi352** [dbarzin/pandora-box#9]
https://github.com/dbarzin/pandora-box/blob/f75e392a4d77e66cde215180841ef82fbc077755/install.sh#L142

Something does not seem right with this line ? :-)

```
-bash: cd: too many arguments
```

Serge

**Comment by dbarzin** [comment]
Maybe with double quote ...

**Comment by dbarzin** [comment]
Fixed here : https://github.com/dbarzin/pandora-box/commit/42aed2c689ba4e8ffec0fcf11c0feaf5ceab2957

**Comment by Foxi352** [comment]
I confirm the fix is working. Installation goes smoothly now.
